version: '3.3'

services:
  db:
    image: mysql:latest
    restart: always
    env_file: .env
    ports:
      - "3308:3306"


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
    ports:
      - "8080:80"